version: '3.9'

services:
  fs.db:
    container_name: fs-db
    image: mysql:latest
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test:
        [
          'CMD',
          '/usr/bin/mysql',
          '--user=root',
          '--password=password',
          '--host=localhost',
          --execute=SHOW TABLES;,
          'sys',
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  fs.mq:
    container_name: fs-mq
    image: rabbitmq:3-management
    hostname: fs-mq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

networks:
  default:
    driver: bridge
